package co.com.grupoasd.services.fixedassets.dtos;

import java.io.Serializable;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@JsonIgnoreProperties(ignoreUnknown = true)
@ApiModel(description = "Information about Areas")
public class AreaDTO implements Serializable {

	private static final long serialVersionUID = -3842710205779744504L;

	@ApiModelProperty(notes = "The area id. it is generated by the service. It won't be updated", required = false)
	private String id;

	@ApiModelProperty(notes = "The area name", required = true)
	private String name;

	@ApiModelProperty(notes = "The city id where area was assigned", required = true)
	private String cityOfAssignmentId;

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCityOfAssignmentId() {
		return cityOfAssignmentId;
	}

	public void setCityOfAssignmentId(String cityOfAssignmentId) {
		this.cityOfAssignmentId = cityOfAssignmentId;
	}

	@Override
	public String toString() {
		return "AreaDTO [id=" + id + ", name=" + name + ", cityOfAssignmentId=" + cityOfAssignmentId + "]";
	}

}
