package co.com.grupoasd.services.fixedassets.dtos;

import java.io.Serializable;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Data Transfer Object for cities
 * 
 * @author egiraldo
 *
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@ApiModel(description = "Information about Cities")
public class CityDTO implements Serializable {

	private static final long serialVersionUID = -7836285903772153258L;

	@ApiModelProperty(notes = "The city id. it is generated by the service. It won't be updated", required = false)
	private String id;

	@ApiModelProperty(notes = "The city name", required = true)
	private String name;

	@ApiModelProperty(notes = "The city code", required = true)
	private String cityCode;

	@ApiModelProperty(notes = "Flag for knowing when city is available to assign an area", required = true)
	private boolean availableToAssignArea;

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCityCode() {
		return cityCode;
	}

	public void setCityCode(String cityCode) {
		this.cityCode = cityCode;
	}

	public boolean isAvailableToAssignArea() {
		return availableToAssignArea;
	}

	public void setAvailableToAssignArea(boolean availableToAssignArea) {
		this.availableToAssignArea = availableToAssignArea;
	}

	@Override
	public String toString() {
		return "CityDTO [id=" + id + ", name=" + name + ", cityCode=" + cityCode + ", availableToAssignArea="
				+ availableToAssignArea + "]";
	}

}
